# Generated by Django 3.1.7 on 2021-02-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210222_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
