# Generated by Django 3.1.7 on 2021-02-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
