# Generated by Django 3.1.7 on 2021-02-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20210227_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
