# Generated by Django 3.1.7 on 2021-03-02 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20210302_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='customer_rated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.customer'),
        ),
    ]
