# Generated by Django 3.1.7 on 2021-03-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_rating_customer_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
