# Generated by Django 3.1.7 on 2021-03-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20210302_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
