# Generated by Django 3.1.7 on 2021-03-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20210302_1411'),
        ('store', '0027_auto_20210302_1422'),
    ]

    operations = [
    ]
