# Generated by Django 3.1.7 on 2021-03-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_merge_20210302_1424'),
        ('store', '0037_merge_20210302_1423'),
    ]

    operations = [
    ]
