# Generated by Django 3.1.7 on 2021-03-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_merge_20210302_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avg_ratings',
        ),
    ]
